# Generated by Django 4.0.5 on 2022-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
