# Generated by Django 4.0.5 on 2022-11-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_email_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
