# Generated by Django 4.0.5 on 2022-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
