# Generated by Django 4.0.5 on 2022-11-22 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0027_remove_connection_connected_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connected_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
