# Generated by Django 4.0.5 on 2022-11-22 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_connection_connected_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='username',
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
