# Generated by Django 4.0.5 on 2022-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
