# Generated by Django 4.0.5 on 2022-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_search_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
