# Generated by Django 4.0.5 on 2022-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_searchmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
