# Generated by Django 4.0.5 on 2022-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_search_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babysitter', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='searchmessage',
            name='date',
        ),
        migrations.AddField(
            model_name='search',
            name='reply',
            field=models.ManyToManyField(blank=True, to='accounts.reply'),
        ),
    ]
