# Generated by Django 4.0.5 on 2022-12-20 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_reply_remove_searchmessage_date_search_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='details',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
