# Generated by Django 4.0.5 on 2022-12-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_profile_gender_alter_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='min_exp',
            field=models.IntegerField(),
        ),
    ]
