# Generated by Django 4.0.5 on 2022-12-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_search_min_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
    ]
