# Generated by Django 4.0.5 on 2022-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='reply',
        ),
        migrations.AddField(
            model_name='search',
            name='reply',
            field=models.ManyToManyField(blank=True, to='accounts.reply'),
        ),
        migrations.RemoveField(
            model_name='search',
            name='results',
        ),
        migrations.AddField(
            model_name='search',
            name='results',
            field=models.ManyToManyField(blank=True, to='accounts.details'),
        ),
    ]
