# Generated by Django 4.0.5 on 2023-01-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchMessage',
            new_name='ReplySearch',
        ),
    ]
